### ISSUE TITLE
play:precompile not use maven-compiler-plugin values

### ISSUE THREAD

**Issue by Neoh59** [play1-maven-plugin/play1-maven-plugin#154]
Hi,

_I'm not sure if it's a bug or if there is a workaround to do what I want._

piece of pom.xml:
```xml
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
        <excludes>
            <exclude>views/**</exclude>
        </excludes>
        <source>1.8</source>
        <target>1.8</target>
    </configuration>
```
as in [play-app-default-parent/pom.xml](https://github.com/play1-maven-plugin/play1-maven-default-parents/blob/master/play-app-default-parent/pom.xml)

If application.conf contains **java.source=1.6** then play:precompile generates Java 6 class files.
If application.conf does not set java.source property, then play:precompile use system java version (ie: 1.7).
It seems to be based on JAVA_HOME like Play! commands. Checked with command: play precompile -version

NB: It's the same for class files inside the war when using play:war.

I expected that maven-compiler-plugin config will manage class files version.
But I think it's managed by play.classloading.ApplicationCompiler.

Maybe it's possible to "simulate" java.source property like Maven dependencies "replace" dependencies.yml file.

Regards

**Comment by gslowikowski** [comment]
Hi
Maven `compiler:compile` and `play:precompile` are completey separate mojos and, unfortunately, I don't see any possibility to eg. define `source` and `target` in one place.

Generally, I can reimplement any Play! functionality written in Python scripts in Maven mojos, but cannot do it with functionalities implemented inside Play! (in Java).
Precompilation is one example. Play! precompiles Java sources AND html templates. I never tried to reimplement template precompilation. Maybe it's possible, maybe would require starting Play! server in "precompile mode", just like in case of "precompile" task.

**Comment by Neoh59** [comment]
OK

I found a workaround. (for me)
I had to add the maven-compiler-plugin to the *plugins* section in my parent pom, and not in the *pluginManagement* section.

Reminder: my JAVA_HOME is Java 8

**Here is the structure of my project:**
~/myproject/pom.xml
  artifactId : myproject
  modules : module : myproject-myapp
  modules : module : myproject-rpm-packaging
  plugins : maven-compiler-plugin : configuration : target : 6
  pluginManagement : maven-compiler-plugin : configuration : target : 7
~/myproject/myproject-myapp/pom.xml
  parent : artifactId : myproject
  nothing about maven-compiler-plugin
  profiles : autodeps and war

Run mvn clean package -P autodeps,war
~/myproject/myproject-myapp/target/classes : java 6
~/myproject/myproject-myapp/target/myapp.war/WEB-INF/application/precompiled/java : java 8
~/myproject/myproject-myapp/precompiled/classes : java 8

Maybe I made a mistake, but pluginManagement:maven-compiler-plugin seems to be useless. (but it is set in the samples).

Any comment/help ?

And what do you think to change play:war to use Maven compiled files instead of Play! precompiled ones ?
I don't know if it's a good idea, or if it's possible.

**Comment by gslowikowski** [comment]
What is your problem (solved by your workaround)? I don't understand.

`maven-compiler-plugin uses Maven configuration. In Maven configuration in `<plugins>` always overrides configuration in `<pluginManagement>/<plugins>`. What you describe is exactly what I would expect.

Classes generated by `play:precompile` have versions controlled by [ApplicationCompiler class](https://github.com/playframework/play1/blob/1.3.2/framework/src/play/classloading/ApplicationCompiler.java#L53:L70). It does not know anything about Maven configuration.

**Comment by Neoh59** [comment]
OK. Sorry. :-)

My workaround is needed to have class files inside the target/classes folder with the Java version set for maven-compiler-plugin. Because maven-compiler-plugin config inside parent pluginMaganement section does not seem to be used (anywhere).
It's not enough but a good first step. :-)

Second point. I understand nothing can be changed for precompiled/java/**.class files.
So I suggest, if it's possible, to use target/classes/**.class files instead. Because these ones are managed by Maven (using maven-compiler-plugin config).

Is it more clear ?

**Comment by gslowikowski** [comment]
Sorry for delay.

`maven-compiler-plugin` `source` and `target` configuration options declared in `pluginManagement/plugins` section are used in compilation process unless you override them by declaring other values in plugin configuration in `plugins` section.

`maven-compiler-plugin` configuration controls only class versions in `target/classes` directory.
These classes are not packaged inside a `war` archive, as you wrote before. `mvn compile` is just the fastest way to check if project code compiles with desired `source` and `target` settings.

I don't know if I could put classes generated by `maven-compiler-plugin` in `.../precompiled/java/` directory of a war file, but what about compiled templates (in `.../precompiled/templates/` directory)?
First, I need to run `play:precompile` to generate them.
Second, I don't think mixing classes generated by `maven-compiler-plugin` with the rest of the content generated by `play:precompile` is good idea. Maybe it would work. I don't know, never tried.

If we could skip `play:precompile` entirely and create war file without compiled templates`, this would have one advantage - speed boost, because `play:precompile` is very slow, especially on large projects.
I don't remember, if application deployed to servlet container, would work without compiled templates. You can check it by deleting `.../precompiled/templates` directory before deployment.
If it would work, maybe we could add some configuration option controlling which classes should be packaged inside a war archive - generated by Maven or Play!
