### ISSUE TITLE
Don't you have some roadmap to transform a normal play proyect in a mavenized one

### ISSUE THREAD

**Issue by hanspoo** [play1-maven-plugin/play1-maven-plugin#167]
Hi,

Our company developed a play 1.4.3 project, and now our client requires to put it in some maven managed environment.

I've seen your project https://github.com/play1-maven-plugin/play1-maven-plugin, the project for mavenizing, i've created the pom.xml, and i'm finding some troubles, first the compiler version (we are using java 8), missing libraries.. ¿ Don't you have some roadmap to transform a normal play proyect in a mavenized one ?

Thanks
Hans

**Comment by gslowikowski** [comment]
There is no roadmap, nobody asked for it before.

Generally, Play! Framework 1.x is not particularly Maven friendly. That's why pom files are very verbose and that was the reason to create default parent poms.

To set compiler version to `1.8` add:

```xml
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <source>1.8</source>
                        <target>1.8</target>
                    </configuration>
                </plugin>
```

to `pom.xml` file and:

```
java.source=1.8
```

to `conf/application.conf` file.

Tell me about your other troubles here.
